export const defaultData = [
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
    { column1: "Data", column2: "Data", column3: "Data", column4: "Data", },
]
export const OngoingProjectsData = [
    { contract: "Jidka D4-57", company: "Galen Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka DG-463", company: "Al-Fansi Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka DG-463", company: "Hilaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka GF-48", company: "Socdaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka GF-48", company: "Socdaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka D4-57", company: "Galen Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka DG-463", company: "Al-Fansi Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka DG-463", company: "Hilaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka GF-48", company: "Socdaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka GF-48", company: "Socdaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka D4-57", company: "Galen Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka D4-57", company: "Galen Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka DG-463", company: "Al-Fansi Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka DG-463", company: "Hilaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka GF-48", company: "Socdaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka GF-48", company: "Socdaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka D4-57", company: "Galen Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka DG-463", company: "Al-Fansi Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka DG-463", company: "Hilaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka GF-48", company: "Socdaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka GF-48", company: "Socdaal Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
    { contract: "Jidka D4-57", company: "Galen Construction", started_date: "01/01/2023", deadline: "01/05/2023", },
];

export const EmplooyeesData = [
    { "id": 1, "first_name": "Ransell", "last_name": "Stodit", "email": "rstodit0@hao123.com", "gender": "Male" },
    { "id": 2, "first_name": "Fielding", "last_name": "Hollyman", "email": "fhollyman1@w3.org", "gender": "Male" },
    { "id": 3, "first_name": "Fredra", "last_name": "Fillary", "email": "ffillary2@tripod.com", "gender": "Female" },
    { "id": 4, "first_name": "Leigh", "last_name": "Royans", "email": "lroyans3@feedburner.com", "gender": "Female" },
    { "id": 5, "first_name": "Olivia", "last_name": "Smees", "email": "osmees4@oakley.com", "gender": "Female" },
    { "id": 6, "first_name": "Nance", "last_name": "Felipe", "email": "nfelipe5@unc.edu", "gender": "Female" },
    { "id": 7, "first_name": "Daphna", "last_name": "Potzold", "email": "dpotzold6@feedburner.com", "gender": "Female" },
    { "id": 8, "first_name": "Sebastiano", "last_name": "Verney", "email": "sverney7@studiopress.com", "gender": "Male" },
    { "id": 9, "first_name": "Annetta", "last_name": "Dungee", "email": "adungee8@csmonitor.com", "gender": "Female" },
    { "id": 10, "first_name": "Donny", "last_name": "Lewty", "email": "dlewty9@eepurl.com", "gender": "Male" },
    { "id": 11, "first_name": "Adrian", "last_name": "Cropton", "email": "acroptona@bbb.org", "gender": "Female" },
    { "id": 12, "first_name": "Roderich", "last_name": "Silbert", "email": "rsilbertb@tamu.edu", "gender": "Male" },
    { "id": 13, "first_name": "Butch", "last_name": "Bread", "email": "bbreadc@spotify.com", "gender": "Male" },
    { "id": 14, "first_name": "Saunder", "last_name": "Bellocht", "email": "sbellochtd@sfgate.com", "gender": "Male" },
    { "id": 15, "first_name": "Tess", "last_name": "Szepe", "email": "tszepee@google.co.uk", "gender": "Female" },
    { "id": 16, "first_name": "Cassondra", "last_name": "De Vere", "email": "cdeveref@mayoclinic.com", "gender": "Female" },
    { "id": 17, "first_name": "Wat", "last_name": "Pesticcio", "email": "wpesticciog@tripod.com", "gender": "Male" },
    { "id": 18, "first_name": "Burt", "last_name": "O'Crevan", "email": "bocrevanh@narod.ru", "gender": "Male" },
    { "id": 19, "first_name": "Merry", "last_name": "Spender", "email": "mspenderi@intel.com", "gender": "Female" },
    { "id": 20, "first_name": "Bertrand", "last_name": "Sebastian", "email": "bsebastianj@wix.com", "gender": "Male" },
    { "id": 21, "first_name": "Natty", "last_name": "Phidgin", "email": "nphidgink@usgs.gov", "gender": "Male" },
    { "id": 22, "first_name": "Christye", "last_name": "Scupham", "email": "cscuphaml@instagram.com", "gender": "Female" },
    { "id": 23, "first_name": "Tracy", "last_name": "Nisard", "email": "tnisardm@auda.org.au", "gender": "Male" },
    { "id": 24, "first_name": "Liza", "last_name": "Tomblings", "email": "ltomblingsn@wikispaces.com", "gender": "Female" },
    { "id": 25, "first_name": "Guillermo", "last_name": "Askey", "email": "gaskeyo@icq.com", "gender": "Male" },
    { "id": 26, "first_name": "Edik", "last_name": "Gives", "email": "egivesp@toplist.cz", "gender": "Male" },
    { "id": 27, "first_name": "Bar", "last_name": "Brockelsby", "email": "bbrockelsbyq@cbslocal.com", "gender": "Male" },
    { "id": 28, "first_name": "Ron", "last_name": "Kidstone", "email": "rkidstoner@china.com.cn", "gender": "Male" },
    { "id": 29, "first_name": "Aloysia", "last_name": "Parke", "email": "aparkes@forbes.com", "gender": "Female" },
    { "id": 30, "first_name": "Wake", "last_name": "Carayol", "email": "wcarayolt@tiny.cc", "gender": "Male" },
    { "id": 31, "first_name": "Randi", "last_name": "Sworn", "email": "rswornu@google.com.hk", "gender": "Male" },
    { "id": 32, "first_name": "Rozelle", "last_name": "Heinz", "email": "rheinzv@chron.com", "gender": "Female" },
    { "id": 33, "first_name": "Christophe", "last_name": "Itzcak", "email": "citzcakw@istockphoto.com", "gender": "Male" },
    { "id": 34, "first_name": "Oby", "last_name": "Reihm", "email": "oreihmx@123-reg.co.uk", "gender": "Male" },
    { "id": 35, "first_name": "Bayard", "last_name": "McTavy", "email": "bmctavyy@slideshare.net", "gender": "Male" },
    { "id": 36, "first_name": "Baxie", "last_name": "Warr", "email": "bwarrz@imgur.com", "gender": "Male" },
    { "id": 37, "first_name": "Rodrick", "last_name": "Lett", "email": "rlett10@jalbum.net", "gender": "Male" },
    { "id": 38, "first_name": "Rosemaria", "last_name": "Tesimon", "email": "rtesimon11@tinyurl.com", "gender": "Female" },
    { "id": 39, "first_name": "Dominga", "last_name": "Shewery", "email": "dshewery12@marriott.com", "gender": "Female" },
    { "id": 40, "first_name": "Angeli", "last_name": "Skaife d'Ingerthorpe", "email": "askaifedingerthorpe13@geocities.com", "gender": "Male" },
    { "id": 41, "first_name": "Conant", "last_name": "Lortz", "email": "clortz14@netscape.com", "gender": "Male" },
    { "id": 42, "first_name": "Ashil", "last_name": "Daveley", "email": "adaveley15@wikipedia.org", "gender": "Female" },
    { "id": 43, "first_name": "Ebony", "last_name": "Poston", "email": "eposton16@seattletimes.com", "gender": "Female" },
]

export const NewData = [
    { "id": 41, "first_name": "Conant", "last_name": "Lortz", "email": "clortz14@netscape.com", "gender": "Male" }
]